name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@DeltaKroneckerGithub_Clash_8171"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "27af95ea-e457-4bc9-9e36-8042ae657f4e"
    sni: "download.xn--mes358a9urctx.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_5293"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "BxceQaOe"
    sni: "t.me/ripaojiedian"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_7549"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "075b9690-f1cc-4d0c-aa1e-f80f07f09815"
    sni: "4o.191292.xyz"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4503"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8QOe)&jIP^]l{P.1"
    sni: "JoInMAHdisErVER-78D.PaGEs.DEV"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6337"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2309"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "2UArZiZkWsgHGMxo6aDSbXbGvFCq5z1o3H2eMoUAn2TFBbaeHDTa4zTyoLPk3o6TA1hTQV9DibygB17ctGeQtvCa5ayGZdTv"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6653"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6345"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "opentunnel.net-imohammad93"
    sni: "ukt-2.opensvr.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2015"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "aes-256-cfb"
    password: "bf7v334KKDV3YDhH"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6807"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3623"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "Uh11bg1NKvjFdgD3gvhqjqrdL2jEm2GUCVMMTKFyubyoDV3wVSQLcYVrhiC7ASHqzA4RivbdXbNKLWQsziRkbm8ndfqLYnmb"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_654"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "f9fa9ed3-1381-441c-8672-588cbedd012d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "r.bibak.bz"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "r.bibak.bz"
  - name: "@DeltaKroneckerGithub_Clash_6725"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2907"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "aes-256-cfb"
    password: "amazonskr05"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3449"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_5783"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "bpb.my79801.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_5859"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "vless.herogoing.top"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tr?ed=2560"
      headers:
        Host: "vless.herogoing.top"
  - name: "@DeltaKroneckerGithub_Clash_5823"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "cf.090227.xyz"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6273"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "trojan"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4211"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "02926f9e-153a-42c8-8ecd-8fade7009ad1"
    sni: "golinkwuxian.top"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_7447"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Aimer"
    sni: "epcco.ambercc.filegear-sg.me"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_7323"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "5a2c16f9"
    sni: "snippets.kkii.eu.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4723"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6115"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.creationlong.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.creationlong.org"
  - name: "@DeltaKroneckerGithub_Clash_7483"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Aimer"
    sni: "epcca.ambercc.filegear-sg.me"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_700"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "02fc59ec-ceb5-4c7b-80cc-8ed7d921c91e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "LonG-eNVIRoNMEnTq83zpUAmzB.winDLEr.CO.uK"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "mizanonline.com.tabnak.ir.snn.ir.alalamtv.net.irannewsdaily.com.presstv.ir.rajanews.com"
  - name: "@DeltaKroneckerGithub_Clash_5705"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "fcspring.ggff.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6053"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "e2f42776-1822-4e5f-8a3d-292071558c48"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1218"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "2041f3f8-1b2e-433e-ab51-f1e3fd0f390b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdp.x5.ru"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "wgXD4k3A16WR0aL63N9Mx8xoqFigJLyQWJXi-l3MPXI"
      short-id: "8ec792bfd725be8a"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_3281"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_5053"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3263"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "/59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_1560"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "04621bae-ab36-11ec-b909-0242ac120002"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_7163"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "0ac0df1b-cfce-47b1-a286-91a0ec2fc7ef"
    sni: "pardazeshvpn-tg7.pages.dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6349"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "22f86840-bcac-11ee-abea-1239d0255272"
    sni: "chatbuzzteambhm.chatbuzzt7150.workers.dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_7225"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "3Ldo ,81m[h)3Lb "
    sni: "azaDnET05.paGEs.dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2393"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "Uh11bg1NKvjFdgD3gvhqjqrdL2jEm2GUCVMMTKFyubyoDV3wVSQLcYVrhiC7ASHqzA4RivbdXbNKLWQsziRkbm8ndfqLYnmb"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2215"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "aes-128-gcm"
    password: "JVrsLLN1tkN8oXZO"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2405"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "YLpDMwoLZi9Dvkr7Q6PCfkwCKJt23MkhD1LHDjnKVjS1R9Z4dD9vY5FffuYCtDVcSzHJLdicZbm4Dh6p8Nsd5d88gzAWYrQY"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4429"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "692650a0-3f10-11f0-8e35-1239d0255272"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_5773"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "bpb.my79801.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2133"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "2BXo2zqYWCHDLhTkQxxFXUpnpFaYiUuNUbBGWQWz4cBa5hGkvLkcdj91tCjBnsDLGdEQDuTcCNVt7MyVyqMvckheuT2Sagio"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_8171"
      - "@DeltaKroneckerGithub_Clash_5293"
      - "@DeltaKroneckerGithub_Clash_7549"
      - "@DeltaKroneckerGithub_Clash_4503"
      - "@DeltaKroneckerGithub_Clash_6337"
      - "@DeltaKroneckerGithub_Clash_2309"
      - "@DeltaKroneckerGithub_Clash_6653"
      - "@DeltaKroneckerGithub_Clash_6345"
      - "@DeltaKroneckerGithub_Clash_2015"
      - "@DeltaKroneckerGithub_Clash_6807"
      - "@DeltaKroneckerGithub_Clash_3623"
      - "@DeltaKroneckerGithub_Clash_654"
      - "@DeltaKroneckerGithub_Clash_6725"
      - "@DeltaKroneckerGithub_Clash_2907"
      - "@DeltaKroneckerGithub_Clash_3449"
      - "@DeltaKroneckerGithub_Clash_5783"
      - "@DeltaKroneckerGithub_Clash_5859"
      - "@DeltaKroneckerGithub_Clash_5823"
      - "@DeltaKroneckerGithub_Clash_6273"
      - "@DeltaKroneckerGithub_Clash_4211"
      - "@DeltaKroneckerGithub_Clash_7447"
      - "@DeltaKroneckerGithub_Clash_7323"
      - "@DeltaKroneckerGithub_Clash_4723"
      - "@DeltaKroneckerGithub_Clash_6115"
      - "@DeltaKroneckerGithub_Clash_7483"
      - "@DeltaKroneckerGithub_Clash_700"
      - "@DeltaKroneckerGithub_Clash_5705"
      - "@DeltaKroneckerGithub_Clash_6053"
      - "@DeltaKroneckerGithub_Clash_1218"
      - "@DeltaKroneckerGithub_Clash_3281"
      - "@DeltaKroneckerGithub_Clash_5053"
      - "@DeltaKroneckerGithub_Clash_3263"
      - "@DeltaKroneckerGithub_Clash_1560"
      - "@DeltaKroneckerGithub_Clash_7163"
      - "@DeltaKroneckerGithub_Clash_6349"
      - "@DeltaKroneckerGithub_Clash_7225"
      - "@DeltaKroneckerGithub_Clash_2393"
      - "@DeltaKroneckerGithub_Clash_2215"
      - "@DeltaKroneckerGithub_Clash_2405"
      - "@DeltaKroneckerGithub_Clash_4429"
      - "@DeltaKroneckerGithub_Clash_5773"
      - "@DeltaKroneckerGithub_Clash_2133"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_8171"
      - "@DeltaKroneckerGithub_Clash_5293"
      - "@DeltaKroneckerGithub_Clash_7549"
      - "@DeltaKroneckerGithub_Clash_4503"
      - "@DeltaKroneckerGithub_Clash_6337"
      - "@DeltaKroneckerGithub_Clash_2309"
      - "@DeltaKroneckerGithub_Clash_6653"
      - "@DeltaKroneckerGithub_Clash_6345"
      - "@DeltaKroneckerGithub_Clash_2015"
      - "@DeltaKroneckerGithub_Clash_6807"
      - "@DeltaKroneckerGithub_Clash_3623"
      - "@DeltaKroneckerGithub_Clash_654"
      - "@DeltaKroneckerGithub_Clash_6725"
      - "@DeltaKroneckerGithub_Clash_2907"
      - "@DeltaKroneckerGithub_Clash_3449"
      - "@DeltaKroneckerGithub_Clash_5783"
      - "@DeltaKroneckerGithub_Clash_5859"
      - "@DeltaKroneckerGithub_Clash_5823"
      - "@DeltaKroneckerGithub_Clash_6273"
      - "@DeltaKroneckerGithub_Clash_4211"
      - "@DeltaKroneckerGithub_Clash_7447"
      - "@DeltaKroneckerGithub_Clash_7323"
      - "@DeltaKroneckerGithub_Clash_4723"
      - "@DeltaKroneckerGithub_Clash_6115"
      - "@DeltaKroneckerGithub_Clash_7483"
      - "@DeltaKroneckerGithub_Clash_700"
      - "@DeltaKroneckerGithub_Clash_5705"
      - "@DeltaKroneckerGithub_Clash_6053"
      - "@DeltaKroneckerGithub_Clash_1218"
      - "@DeltaKroneckerGithub_Clash_3281"
      - "@DeltaKroneckerGithub_Clash_5053"
      - "@DeltaKroneckerGithub_Clash_3263"
      - "@DeltaKroneckerGithub_Clash_1560"
      - "@DeltaKroneckerGithub_Clash_7163"
      - "@DeltaKroneckerGithub_Clash_6349"
      - "@DeltaKroneckerGithub_Clash_7225"
      - "@DeltaKroneckerGithub_Clash_2393"
      - "@DeltaKroneckerGithub_Clash_2215"
      - "@DeltaKroneckerGithub_Clash_2405"
      - "@DeltaKroneckerGithub_Clash_4429"
      - "@DeltaKroneckerGithub_Clash_5773"
      - "@DeltaKroneckerGithub_Clash_2133"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_8171"
      - "@DeltaKroneckerGithub_Clash_5293"
      - "@DeltaKroneckerGithub_Clash_7549"
      - "@DeltaKroneckerGithub_Clash_4503"
      - "@DeltaKroneckerGithub_Clash_6337"
      - "@DeltaKroneckerGithub_Clash_2309"
      - "@DeltaKroneckerGithub_Clash_6653"
      - "@DeltaKroneckerGithub_Clash_6345"
      - "@DeltaKroneckerGithub_Clash_2015"
      - "@DeltaKroneckerGithub_Clash_6807"
      - "@DeltaKroneckerGithub_Clash_3623"
      - "@DeltaKroneckerGithub_Clash_654"
      - "@DeltaKroneckerGithub_Clash_6725"
      - "@DeltaKroneckerGithub_Clash_2907"
      - "@DeltaKroneckerGithub_Clash_3449"
      - "@DeltaKroneckerGithub_Clash_5783"
      - "@DeltaKroneckerGithub_Clash_5859"
      - "@DeltaKroneckerGithub_Clash_5823"
      - "@DeltaKroneckerGithub_Clash_6273"
      - "@DeltaKroneckerGithub_Clash_4211"
      - "@DeltaKroneckerGithub_Clash_7447"
      - "@DeltaKroneckerGithub_Clash_7323"
      - "@DeltaKroneckerGithub_Clash_4723"
      - "@DeltaKroneckerGithub_Clash_6115"
      - "@DeltaKroneckerGithub_Clash_7483"
      - "@DeltaKroneckerGithub_Clash_700"
      - "@DeltaKroneckerGithub_Clash_5705"
      - "@DeltaKroneckerGithub_Clash_6053"
      - "@DeltaKroneckerGithub_Clash_1218"
      - "@DeltaKroneckerGithub_Clash_3281"
      - "@DeltaKroneckerGithub_Clash_5053"
      - "@DeltaKroneckerGithub_Clash_3263"
      - "@DeltaKroneckerGithub_Clash_1560"
      - "@DeltaKroneckerGithub_Clash_7163"
      - "@DeltaKroneckerGithub_Clash_6349"
      - "@DeltaKroneckerGithub_Clash_7225"
      - "@DeltaKroneckerGithub_Clash_2393"
      - "@DeltaKroneckerGithub_Clash_2215"
      - "@DeltaKroneckerGithub_Clash_2405"
      - "@DeltaKroneckerGithub_Clash_4429"
      - "@DeltaKroneckerGithub_Clash_5773"
      - "@DeltaKroneckerGithub_Clash_2133"

rules:
  - MATCH,PROXY
